{
 "title": "Flask Monitoring",
 "description": "Monitor Flask application through custom StatsD metrics with Prometheus and Grafana.",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "app_name",
    "label": "Application Name",
    "query": {
     "query": "label_values(flask_info{}, app_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cache Hitrate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cache_hit_total/total_number_counter_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests Average Duration",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flask_http_request_duration_seconds_sum / flask_http_request_duration_seconds_count",
     "legendFormat": "[{{status}}] {{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum (flask_http_request_total)" }
   ]
  },
  {
   "title": "Requests Per Status Code",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (flask_http_request_total) by(status)",
     "legendFormat": "HTTP Status: {{status}}"
    }
   ]
  },
  {
   "title": "Requests Per Second",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(flask_http_request_duration_seconds_count[1m])",
     "legendFormat": "{{status}} {{path}}"
    }
   ]
  },
  {
   "title": "Requests Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "flask_http_request_duration_seconds_count",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Request Average Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "flask_http_request_duration_seconds_sum / flask_http_request_duration_seconds_count",
     "legendFormat": "{{status}} {{path}}"
    }
   ]
  },
  {
   "title": "Percent of 2xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(flask_http_request_duration_seconds_bucket{status=~\"2.*\"}) by(path, method) / sum(flask_http_request_duration_seconds_bucket) by(path, method)",
     "legendFormat": "{{method}} {{path}} "
    }
   ]
  },
  {
   "title": "Percent of 5xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(flask_http_request_duration_seconds_bucket{status=~\"5.*\"}) by(endpoint, method) / sum(flask_http_request_duration_seconds_bucket) by(endpoint, method)",
     "legendFormat": "{{method}} {{endpoint}} "
    }
   ]
  }
 ]
}