server:
  port: 0

spring:
  application:
    name: user-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

  cloud:
    config:
      import-check:
        enabled: false
      name: userservice
  config:
#    import: "optional:configserver:http://config-service:8888"
    import: "optional:configserver:http://localhost:8888"

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
        defaultZone: http://localhost:8761/eureka

welcome:
  message: Roombination.
  secondmessage: Roombi.

logging:
  level:
    roombi.server.userservice: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: refresh, beans, health, busrefresh, info, metrics, prometheus

