server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/cosy363/config-server
          username: cosy363
          password: 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


