version: "3"
services:
  master:
    image: mysql:5.7
    platform: linux/amd64
    container_name: mysql-master
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - /Users/brannynew/Documents/Roombination/Roombination/mysql/db

  slave:
    image: mysql:5.7
    platform: linux/amd64
    container_name: mysql-slave
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - /Users/brannynew/Documents/Roombination/Roombination/mysql/db